CREATE TABLE tb_endereco (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cl_estado VARCHAR(255),
    cl_cidade VARCHAR(255),
    cl_rua VARCHAR(255),
    cl_numero INT,
    cl_cep VARCHAR(255)
);
