CREATE TABLE tb_consulta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cl_data_hora TIMESTAMP,
    paciente_id BIGINT NOT NULL,
    FOREIGN KEY (paciente_id) REFERENCES tb_paciente(id)
);
